version: '3'
services:
  postgres:
    image: postgres
    hostname: postgres
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: etalon
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    restart: unless-stopped

    
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

  api:
    build:
      context: api
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - ipcamera
    ports:
      - "8000:8000"
    volumes:
      - ./api:/usr/src/api

  ipcamera:
    build: ./ipcamera
    hostname: ipcamera
    volumes:
      - ./ipcamera/loop.mp4:/loop.mp4